services:
  request:
    image: request
    build:
      context: .
      dockerfile: ReQuest/Dockerfile

  request-backend:
    image: request-backend
    build:
      context: .
      dockerfile: ReQuest-backend/Dockerfile

